# Generated by Django 5.0.1 on 2024-01-11 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blurb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('order', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('logo', models.CharField()),
                ('color', models.CharField()),
                ('website', models.CharField()),
                ('join_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlurbHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('blurb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.blurb')),
            ],
        ),
        migrations.CreateModel(
            name='BlurbList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OL', 'Ordered List'), ('UL', 'Unordered List')])),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.blurb')),
            ],
        ),
        migrations.CreateModel(
            name='BlurbListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.IntegerField(null=True)),
                ('blurb_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.blurblist')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('location', models.CharField()),
                ('contract_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CO', 'Contract'), ('FR', 'Freelance')])),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='blurb',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job'),
        ),
    ]
